# Generated by Django 5.0.3 on 2024-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opensourceproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensourceproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10),
        ),
    ]
